# Generated by Django 3.2.7 on 2021-12-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_rename_statusupload_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='owner',
        ),
    ]
