# Generated by Django 3.2.7 on 2021-12-22 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0003_remove_status_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='body',
            field=models.TextField(blank=True, default='null'),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(blank=True, default='null', max_length=100),
        ),
    ]
