# Generated by Django 3.2.7 on 2021-12-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_auto_20211222_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
